[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/focal/mattermost-k8s-27
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mattermost-k8s/0 [allocating] waiting: installing agent
  mattermost-k8s/1 [allocating] waiting: installing agent
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mattermost-k8s/0 [executing] waiting: Waiting for database relation
  mattermost-k8s/1 [executing] waiting: Waiting for database relation
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mattermost-k8s/0 [idle] waiting: Waiting for database relation
  mattermost-k8s/1 [idle] waiting: Waiting for database relation
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mattermost-k8s/0 [executing] active: 
  mattermost-k8s/1 [executing] waiting: Waiting for database relation
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  mattermost-k8s/0 [executing] active: 
  mattermost-k8s/1 [executing] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:46:39Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
pgbouncer-k8s             1.21.0   active      2  pgbouncer-k8s                              0  10.152.183.185  no       
postgresql-k8s            14.13    active      3  postgresql-k8s            14/edge        398  10.152.183.238  no       
postgresql-test-app                active      1  postgresql-test-app       latest/edge    248  10.152.183.212  no       received database credentials of the first database
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  10.152.183.201  no       

Unit                         Workload  Agent  Address     Ports  Message
pgbouncer-k8s/0              active    idle   10.1.83.8          
pgbouncer-k8s/1*             active    idle   10.1.83.9          
postgresql-k8s/0             active    idle   10.1.83.15         
postgresql-k8s/1             active    idle   10.1.83.16         
postgresql-k8s/2*            active    idle   10.1.83.17         Primary
postgresql-test-app/0*       active    idle   10.1.83.10         received database credentials of the first database
self-signed-certificates/0*  active    idle   10.1.83.14         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-1: 01:36:37 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-0: 01:36:37 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:37:22 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:38:35 ERROR unit.postgresql-k8s/1.juju-log failed to change plugins: 
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 326, in enable_disable_extensions
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 150, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.test.svc.cluster.local" (10.152.183.99), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 707, in _handle_enable_disable_extensions
    self.postgresql.enable_disable_extensions(extensions, database)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 353, in enable_disable_extensions
    raise PostgreSQLEnableDisableExtensionError()
charms.postgresql_k8s.v0.postgresql.PostgreSQLEnableDisableExtensionError
controller-0: 01:46:37 ERROR juju.worker.caasunitprovisioner stopping application worker for mattermost-k8s: Operation cannot be fulfilled on deployments.apps "mattermost-k8s": the object has been modified; please apply your changes to the latest version and try again

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...