[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.5    unsupported  01:45:35Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Address         Exposed  Message
data-integrator                    active      1  data-integrator           latest/edge     45  10.152.183.26   no       
pgbouncer-k8s             1.21.0   active      1  pgbouncer-k8s                              0  10.152.183.167  no       
postgresql-k8s            14.12    active      3  postgresql-k8s            14/edge        385  10.152.183.45   no       
postgresql-test-app                active      1  postgresql-test-app       latest/edge    242  10.152.183.144  no       received database credentials of the first database
postgresql-test-app2               active      1  postgresql-test-app       latest/edge    242  10.152.183.138  no       received database credentials of the first database
self-signed-certificates           active      1  self-signed-certificates  latest/stable  155  10.152.183.247  no       

Unit                         Workload  Agent  Address       Ports  Message
data-integrator/0*           active    idle   10.1.150.201         
pgbouncer-k8s/0*             active    idle   10.1.150.200         
postgresql-k8s/0*            active    idle   10.1.150.207         
postgresql-k8s/1             active    idle   10.1.150.208         
postgresql-k8s/2             active    idle   10.1.150.209         
postgresql-test-app2/0*      active    idle   10.1.150.206         received database credentials of the first database
postgresql-test-app/0*       active    idle   10.1.150.202         received database credentials of the first database
self-signed-certificates/0*  active    idle   10.1.150.210         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-2: 01:43:07 ERROR unit.postgresql-k8s/2.juju-log failed to change plugins: 
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 307, in enable_disable_extensions
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 131, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.test.svc.cluster.local" (10.152.183.92), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/./src/charm.py", line 686, in _handle_enable_disable_extensions
    self.postgresql.enable_disable_extensions(extensions, database)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 333, in enable_disable_extensions
    raise PostgreSQLEnableDisableExtensionError()
charms.postgresql_k8s.v0.postgresql.PostgreSQLEnableDisableExtensionError

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...