[32mINFO    [0m httpx:_client.py:1773 HTTP Request: DELETE https://10.1.0.105:16443/api/v1/namespaces/test/pods/pgbouncer-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-test-app/0 [idle] active: received database credentials of the second database
  postgresql-k8s/0 [idle] active: Primary
  postgresql-k8s/1 [idle] active: 
  pgbouncer-k8s/0 [executing] maintenance: stopping charm software
  pgbouncer-k8s/1 [idle] active: 
  secondary-application/0 [idle] active: received database credentials of the second database
  finos-waltz-k8s/0 [idle] active: 
  pgbouncer-k8s-secondary/0 [idle] active: 
  data-integrator/0 [idle] active: 
  indico/0 [idle] active: 
  redis-broker/0 [idle] active: 
  redis-cache/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:52:01Z

App                      Version               Status  Scale  Charm                Channel        Rev  Address         Exposed  Message
data-integrator                                active      1  data-integrator      latest/edge     38  10.152.183.134  no       
finos-waltz-k8s                                active      1  finos-waltz-k8s      latest/edge     33  10.152.183.148  no       
indico                   3.3.1                 active      1  indico               latest/stable  213  10.152.183.89   no       
pgbouncer-k8s            1.21.0                active      2  pgbouncer-k8s                         0  10.152.183.62   no       
pgbouncer-k8s-secondary  1.21.0                active      1  pgbouncer-k8s                         1  10.152.183.67   no       
postgresql-k8s           14.12                 active      2  postgresql-k8s       14/edge        327  10.152.183.177  no       
postgresql-test-app                            active      1  postgresql-test-app  latest/edge    190  10.152.183.136  no       received database credentials of the second database
redis-broker             ubuntu/redis@691f315  active      1  redis-k8s            latest/stable    7                  no       
redis-cache              ubuntu/redis@691f315  active      1  redis-k8s            latest/stable    7                  no       
secondary-application                          active      1  postgresql-test-app  latest/edge    190  10.152.183.196  no       received database credentials of the second database

Unit                        Workload  Agent  Address      Ports     Message
data-integrator/0*          active    idle   10.1.82.212            
finos-waltz-k8s/0*          active    idle   10.1.82.209            
indico/0*                   active    idle   10.1.82.215            
pgbouncer-k8s-secondary/0*  active    idle   10.1.82.210            
pgbouncer-k8s/0*            active    idle   10.1.82.220            
pgbouncer-k8s/1             active    idle   10.1.82.211            
postgresql-k8s/0*           active    idle   10.1.82.205            Primary
postgresql-k8s/1            active    idle   10.1.82.206            
postgresql-test-app/0*      active    idle   10.1.82.200            received database credentials of the second database
redis-broker/0*             active    idle   10.1.82.217  6379/TCP  
redis-cache/0*              active    idle   10.1.82.219  6379/TCP  
secondary-application/0*    active    idle   10.1.82.208            received database credentials of the second database

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

unit-postgresql-test-app-0: 01:37:18 ERROR unit.postgresql-test-app/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 504, in <module>
    main(ApplicationCharm)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 432, in _on_run_sql_action
    cursor.execute(query)
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

application-redis-cache: 01:49:33 ERROR unit.redis-cache/0.juju-log redis:20: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 159, in <module>
    main(RedisCharm)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/lib/charms/redis_k8s/v0/redis.py", line 91, in _on_relation_changed
    event.relation.data[self.model.unit]['hostname'] = str(self._bind_address(event))
  File "/var/lib/juju/agents/unit-redis-cache-0/charm/lib/charms/redis_k8s/v0/redis.py", line 103, in _bind_address
    return self.app.name
AttributeError: 'RedisProvides' object has no attribute 'app'
application-redis-cache: 01:49:33 ERROR juju.worker.caasoperator.uniter.redis-cache/0.operation hook "redis-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-pgbouncer-k8s-0: 01:51:09 ERROR unit.pgbouncer-k8s/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...