[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
  pgbouncer-k8s/0 [executing] active: 
  pgbouncer-k8s/1 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] waiting: waiting for backend-database relation to connect
  pgbouncer-k8s/1 [idle] blocked: waiting for backend database relation to initialise
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] blocked: waiting for backend database relation to initialise
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.4    unsupported  01:43:54Z

App            Version  Status   Scale  Charm          Channel  Rev  Address         Exposed  Message
pgbouncer-k8s  1.21.0   waiting      2  pgbouncer-k8s             0  10.152.183.185  no       installing agent

Unit              Workload  Agent  Address      Ports  Message
pgbouncer-k8s/0   blocked   idle   10.1.117.72         waiting for backend database relation to initialise
pgbouncer-k8s/1*  blocked   idle   10.1.117.74         waiting for backend database relation to initialise

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

controller-0: 01:42:18 ERROR juju.worker.caasapplicationprovisioner.runner exited "finos-waltz": getting OCI image resources: unable to fetch OCI image resources for finos-waltz: application "finos-waltz" dying or dead
unit-pgbouncer-k8s-0: 01:43:09 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "5929bd34-51ba-4863-803e-5caf15c88f82:r#5#postgresql-k8s": settings 5929bd34-51ba-4863-803e-5caf15c88f82:r#5#postgresql-k8s not found (not found)
unit-postgresql-k8s-2: 01:43:09 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "5929bd34-51ba-4863-803e-5caf15c88f82:r#5#pgbouncer-k8s": settings 5929bd34-51ba-4863-803e-5caf15c88f82:r#5#pgbouncer-k8s not found (not found)
unit-pgbouncer-k8s-0: 01:43:19 ERROR unit.pgbouncer-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 1045, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 395, in _on_pgbouncer_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "metrics_server" (cannot start service: exited quickly with code 0)
----- Logs from task 0 -----
2024-07-24T01:43:18Z INFO Service "metrics_server" already stopped.
----- Logs from task 1 -----
2024-07-24T01:43:18Z INFO Service "pgbouncer_0" already started.
----- Logs from task 2 -----
2024-07-24T01:43:18Z INFO Service "pgbouncer_1" already started.
----- Logs from task 3 -----
2024-07-24T01:43:18Z INFO Service "pgbouncer_2" already started.
----- Logs from task 4 -----
2024-07-24T01:43:18Z INFO Service "pgbouncer_3" already started.
----- Logs from task 6 -----
2024-07-24T01:43:19Z INFO Most recent service output:
    ts=2024-07-24T01:38:57.672Z caller=collector.go:469 level=info msg="Starting scrape"
    ts=2024-07-24T01:38:57.675Z caller=pgbouncer_exporter.go:66 level=info msg="Starting pgbouncer_exporter" version="(version=, branch=, revision=)"
    ts=2024-07-24T01:38:57.675Z caller=pgbouncer_exporter.go:67 level=info msg="Build context" build_context="(go=go1.18.1, user=, date=)"
    ts=2024-07-24T01:38:57.675Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9127
    ts=2024-07-24T01:38:57.675Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9127
2024-07-24T01:43:19Z ERROR cannot start service: exited quickly with code 0
-----
unit-pgbouncer-k8s-0: 01:43:19 ERROR juju.worker.uniter.operation hook "pgbouncer-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-pgbouncer-k8s-0: 01:43:19 ERROR juju.worker.uniter pebble poll failed for container "pgbouncer": failed to send pebble-ready event: hook failed

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...