[32mINFO    [0m integration.test_upgrade_data_integrator:test_upgrade_data_integrator.py:108 Refresh the charm
[32mINFO    [0m integration.test_upgrade_data_integrator:test_upgrade_data_integrator.py:111 Wait for upgrade to start
[32mINFO    [0m integration.test_upgrade_data_integrator:test_upgrade_data_integrator.py:118 Wait for upgrade to complete on first upgrading unit
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] waiting: other units upgrading first...
  pgbouncer-k8s/1 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] waiting: other units upgrading first...
  pgbouncer-k8s/1 [idle] active: 
[32mINFO    [0m integration.test_upgrade_data_integrator:test_upgrade_data_integrator.py:126 Resume upgrade
[32mINFO    [0m integration.test_upgrade_data_integrator:test_upgrade_data_integrator.py:131 Wait for upgrade to complete
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [executing] maintenance: stopping charm software
  pgbouncer-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [executing] blocked: K8s service not connectable
  pgbouncer-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.5    unsupported  01:43:32Z

App              Version  Status  Scale  Charm            Channel      Rev  Address         Exposed  Message
data-integrator           error       2  data-integrator  latest/edge  145  10.152.183.214  no       hook failed: "secret-changed"
pgbouncer-k8s    1.21.0   active      2  pgbouncer-k8s                   0  10.152.183.168  no       
postgresql-k8s   14.17    active      3  postgresql-k8s   14/edge      576  10.152.183.217  no       

Unit                Workload  Agent  Address      Ports  Message
data-integrator/0*  active    idle   10.1.36.139         
data-integrator/1   error     idle   10.1.36.140         hook failed: "secret-changed"
pgbouncer-k8s/0*    active    idle   10.1.36.148         
pgbouncer-k8s/1     active    idle   10.1.36.147         
postgresql-k8s/0*   active    idle   10.1.36.144         Primary
postgresql-k8s/1    active    idle   10.1.36.145         
postgresql-k8s/2    active    idle   10.1.36.146         

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-postgresql-k8s-2: 01:38:24 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:38:25 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-2: 01:39:01 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-pgbouncer-k8s-1: 01:41:04 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:41:05 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:41:07 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:41:08 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:41:09 ERROR unit.pgbouncer-k8s/1.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/src/charm.py", line 1146, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/src/charm.py", line 366, in _on_pgbouncer_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/model.py", line 2440, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2178, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-1/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2278, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "metrics_server" (service start attempt: exited quickly with code 1, will restart)
----- Logs from task 5 -----
2025-04-25T01:41:08Z INFO Most recent service output:
    ts=2025-04-25T01:41:08.695Z caller=collector.go:138 level=error msg="error setting up DB connection" err="error pinging pgbouncer: dial tcp [::1]:6432: connect: connection refused"
2025-04-25T01:41:08Z ERROR service start attempt: exited quickly with code 1, will restart
-----
unit-pgbouncer-k8s-1: 01:41:09 ERROR juju.worker.uniter.operation hook "pgbouncer-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-pgbouncer-k8s-1: 01:41:09 ERROR juju.worker.uniter pebble poll failed for container "pgbouncer": failed to send pebble-ready event: hook failed
unit-pgbouncer-k8s-0: 01:42:13 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...