[32mINFO    [0m integration.relations.test_db:test_db.py:183 Deploying test app
[32mINFO    [0m juju.model:model.py:2098 Deploying ch:amd64/jammy/postgresql-test-app-211
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.relations.test_db:test_db.py:187 Wait for PGB to block due to extensions
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [executing] blocked: bad relation request - remote app requested extensions, which are unsupported. Please remove this relation.
  pgbouncer-k8s/1 [executing] active: 
  pgbouncer-k8s/2 [executing] active: 
[32mINFO    [0m integration.relations.test_db:test_db.py:195 Rerelate with extensions enabled
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
[33mWARNING [0m juju.model:model.py:1564 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [executing] active: 
  pgbouncer-k8s/2 [idle] active: 
  postgresql-test-app/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2972 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
  postgresql-test-app/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:903 Model status:

Model  Controller          Cloud/Region        Version  SLA          Timestamp
test   microk8s-localhost  microk8s/localhost  3.4.6    unsupported  01:56:42Z

App                  Version  Status  Scale  Charm                Channel        Rev  Address         Exposed  Message
pgbouncer-k8s        1.21.0   active      3  pgbouncer-k8s                         0  10.152.183.195  no       
postgresql-k8s       14.13    active      3  postgresql-k8s       14/edge        431  10.152.183.78   no       
postgresql-test-app           active      1  postgresql-test-app  latest/stable  211  10.152.183.121  no       

Unit                    Workload  Agent  Address      Ports  Message
pgbouncer-k8s/0*        active    idle   10.1.174.73         
pgbouncer-k8s/1         active    idle   10.1.174.75         
pgbouncer-k8s/2         active    idle   10.1.174.74         
postgresql-k8s/0        active    idle   10.1.174.79         
postgresql-k8s/1        active    idle   10.1.174.80         
postgresql-k8s/2*       active    idle   10.1.174.81         Primary
postgresql-test-app/0*  active    idle   10.1.174.83         

[32mINFO    [0m pytest_operator.plugin:plugin.py:909 Juju error logs:

unit-postgresql-k8s-0: 01:47:15 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:47:15 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:47:15 ERROR unit.postgresql-k8s/1.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:47:15 ERROR unit.postgresql-k8s/1.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:47:48 ERROR unit.postgresql-k8s/1.juju-log database-peers:0: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_socket.py", line 118, in recv
    bytes_ = _recv()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_socket.py", line 97, in _recv
    return sock.recv(bufsize)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/pebble.py", line 2906, in exec
    control_ws = self._connect_websocket(task_id, 'control')
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/pebble.py", line 2994, in _connect_websocket
    ws.connect(url, socket=sock)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_core.py", line 261, in connect
    self.handshake_response = handshake(self.sock, url, *addrs, **options)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_handshake.py", line 141, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_http.py", line 351, in read_headers
    line = recv_line(sock)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_socket.py", line 140, in recv_line
    c = recv(sock, 1)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/websocket/_socket.py", line 120, in recv
    raise WebSocketTimeoutException("Connection timed out")
websocket._exceptions.WebSocketTimeoutException: Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 2245, in <module>
    main(PostgresqlOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/__init__.py", line 343, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/_main.py", line 543, in main
    manager.run()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/_main.py", line 529, in run
    self._emit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/_main.py", line 515, in _emit
    self.framework.reemit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 867, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/framework.py", line 947, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 932, in _on_postgresql_pebble_ready
    self._create_pgdata(container)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 734, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/./src/charm.py", line 908, in _create_pgdata
    container.exec([
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/model.py", line 2996, in exec
    return self._pebble.exec(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/ops/pebble.py", line 2915, in exec
    raise ChangeError(change.err, change) from e
ops.pebble.ChangeError: cannot perform the following tasks:
- exec command "chown" (exec 23: timeout waiting for websocket connections: context deadline exceeded)
----- Logs from task 0 -----
2024-10-30T01:47:48Z ERROR exec 23: timeout waiting for websocket connections: context deadline exceeded
-----
unit-postgresql-k8s-1: 01:47:49 ERROR juju.worker.uniter.operation hook "database-peers-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-postgresql-k8s-0: 01:49:00 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:00 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:13 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:13 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:26 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:26 ERROR unit.postgresql-k8s/0.juju-log database:5: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:49:39 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:49:39 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:40 ERROR unit.postgresql-k8s/0.juju-log database-peers:0: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:49:40 ERROR unit.postgresql-k8s/0.juju-log database-peers:0: This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:49:52 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:49:52 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:50:05 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:50:05 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:50:18 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:50:18 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-pgbouncer-k8s-0: 01:55:30 ERROR unit.pgbouncer-k8s/0.juju-log db:9: ERROR - `extensions` (pg_trgm:public, unaccent:public) cannot be requested through relations - Please enable extensions through `juju config` and add the relation again.
unit-postgresql-k8s-1: 01:56:04 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-1: 01:56:04 ERROR unit.postgresql-k8s/1.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:56:04 ERROR unit.postgresql-k8s/0.juju-log This operation (update_relation_data()) can only be performed by the leader unit
unit-postgresql-k8s-0: 01:56:04 ERROR unit.postgresql-k8s/0.juju-log This operation (update_relation_data()) can only be performed by the leader unit

[32mINFO    [0m pytest_operator.plugin:plugin.py:991 Forgetting model main...