[32mINFO    [0m integration.test_upgrade:test_upgrade.py:157 starting continuous writes to the database
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:161 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:164 Get leader unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:170 Run pre-upgrade-check action
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:178 Inject dependency fault
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:183 Refresh the charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:186 Get first upgrading unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:190 Wait for upgrade to fail on first upgrading unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:197 Ensure continuous_writes while in failure state on remaining units
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:200 Re-run pre-upgrade-check action
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:204 Re-refresh the charm
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] waiting: other units upgrading first...
  pgbouncer-k8s/1 [idle] waiting: other units upgrading first...
  pgbouncer-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] waiting: other units upgrading first...
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:211 Resume upgrade
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:215 Wait for application to recover
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [executing] maintenance: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [executing] maintenance: 
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  pgbouncer-k8s/0 [idle] active: 
  pgbouncer-k8s/1 [idle] active: 
  pgbouncer-k8s/2 [idle] active: 
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:219 Ensure continuous_writes after rollback procedure
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:224 Checking whether no writes were lost
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.32:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m pytest_operator.plugin:plugin.py:937 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.5    unsupported  01:52:23Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
pgbouncer-k8s        1.21.0   active      3  pgbouncer-k8s                       2  10.152.183.201  no       
postgresql-k8s       14.17    active      3  postgresql-k8s       14/edge      581  10.152.183.57   no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  379  10.152.183.119  no       received database credentials of the first database

Unit                    Workload  Agent  Address     Ports  Message
pgbouncer-k8s/0         active    idle   10.1.14.89         
pgbouncer-k8s/1         active    idle   10.1.14.88         
pgbouncer-k8s/2*        active    idle   10.1.14.87         
postgresql-k8s/0        active    idle   10.1.14.80         
postgresql-k8s/1        active    idle   10.1.14.81         
postgresql-k8s/2*       active    idle   10.1.14.82         Primary
postgresql-test-app/0*  active    idle   10.1.14.73         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:943 Juju error logs:

unit-postgresql-k8s-0: 01:42:14 ERROR unit.postgresql-k8s/0.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-pgbouncer-k8s-2: 01:46:05 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-2: 01:46:07 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:47:06 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:47:08 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:47:09 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:47:11 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:47:44 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:47:46 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:47:47 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:47:49 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-2: 01:49:24 ERROR unit.pgbouncer-k8s/2.juju-log charms.data_platform_libs.v0.upgrade.VersionError - {'message': 'Versions incompatible, charm 1 can not be upgraded to 15.0', 'cause': 'Upgrades only supported for specific versions, charm versions satisfying requirement ^15', 'resolution': ''}
unit-pgbouncer-k8s-2: 01:49:31 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-2: 01:49:32 ERROR unit.pgbouncer-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/src/charm.py", line 1146, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/__init__.py", line 347, in __call__
    return _main.main(charm_class=charm_class, use_juju_for_storage=use_juju_for_storage)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 565, in main
    manager.run()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 550, in run
    self._emit()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 502, in _emit
    self._emit_charm_event(self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/_main.py", line 537, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 907, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 997, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/src/charm.py", line 366, in _on_pgbouncer_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/model.py", line 2440, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2178, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-2/charm/venv/lib/python3.10/site-packages/ops/pebble.py", line 2278, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "metrics_server" (service start attempt: exited quickly with code 1, will restart)
----- Logs from task 5 -----
2025-04-26T01:49:31Z INFO Most recent service output:
    ts=2025-04-26T01:49:31.904Z caller=collector.go:138 level=error msg="error setting up DB connection" err="error pinging pgbouncer: dial tcp [::1]:6432: connect: connection refused"
2025-04-26T01:49:31Z ERROR service start attempt: exited quickly with code 1, will restart
-----
unit-pgbouncer-k8s-2: 01:49:33 ERROR juju.worker.uniter.operation hook "pgbouncer-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-pgbouncer-k8s-2: 01:49:33 ERROR juju.worker.uniter pebble poll failed for container "pgbouncer": failed to send pebble-ready event: hook failed
unit-pgbouncer-k8s-2: 01:50:10 ERROR unit.pgbouncer-k8s/2.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:51:07 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:51:08 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:51:10 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-1: 01:51:11 ERROR unit.pgbouncer-k8s/1.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:51:31 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:51:33 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:51:34 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running
unit-pgbouncer-k8s-0: 01:51:35 ERROR unit.pgbouncer-k8s/0.juju-log pgbouncer not running

[32mINFO    [0m pytest_operator.plugin:plugin.py:1025 Forgetting model main...